server:
  port: 7552

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:9000/eureka

spring:
  application:
    name: tasks
  profiles:
    active: dev
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true